AWSTemplateFormatVersion: 2010-09-09
Description: Master stack which creates all required nested stacks
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: Project Details
        Parameters:
          - ProjectName
      - Label:
          default: VPC Network Details
        Parameters:
          - VPCCIDR
          - Subnet1CidrBlock
          - Subnet2CidrBlock
      - Label:
          default: ECR Repository Details
        Parameters:
          - ECRRepositoryName
      - Label:
          default: Code Bucket Repository Name
        Parameters:
          - SourceBucket
      - Label:
          default: Access to Service Catalog
        Parameters:
          - AdminGroupName
          - UserGroupName
      - Label:
          default: Resource Creation
        Parameters:
          - LayerName
          - PortfolioName
          - ProductName
    ParameterLabels:
      VPCCIDR:
        default: VPC CIDR block
      Subnet1CidrBlock:
        default: Resource Subnet CIDR block
      Subnet2CidrBlock:
        default: ENI Subnet CIDR block
      ECRRepositoryName:
        default: ECR Repository Name
      SourceBucket:
        default: Source Bucket Name
      AdminGroupName:
        default: Admin Group Name
      UserGroupName:
        default: User Group Name
      LayerName:
        default: Python Layer Name
      PortfolioName:
        default: Service Catalog Portfolio Name
      ProductName:
        default: Service Catalog Product Name
Parameters:
  ProjectName:
    Description: Project name for the SageMakerGuardrail solution
    Type: String
    Default: SageMaker
  VPCCIDR:
    AllowedPattern: >-
      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.0.0/16
    Description: CIDR block for the VPC
    Type: String
  ECRRepositoryName:
    Description: ECR Repository Name
    Type: String
    Default: sagemaker_repository
  Subnet1CidrBlock:
    Description: CIDR for the Subnet-1
    Type: String
    Default: 10.0.1.0/24
  Subnet2CidrBlock:
    Description: CIDR for the Subnet-2
    Type: String
    Default: 10.0.2.0/24
  SourceBucket:
    Description: Source Bucket Name where All cloudformation templates are stored
    Type: String
    Default: code-repository-california
  AdminGroupName:
    Description: Admin group Name
    Type: String
    Default: AdminGroup
  UserGroupName:
    Description: User group name who will access Service Catalog
    Type: String
    Default: SCUsers
  LayerName:
    Description: Name of the Lambda Layer
    Type: String
    Default: Boto3Module
  PortfolioName:
    Description: Name of the Service Catalog Portfoilio
    Type: String
    Default: SageMaker_Portfolio
  ProductName:
    Description: Name of the Sagemaker Product
    Type: String
    Default: SageMaker_Product
Resources:
  VPCStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Join 
        - ''
        - - 'https://s3.amazonaws.com/'
          - !Ref SourceBucket
          - /VPCStack.json
      TimeoutInMinutes: '5'
      Parameters:
        ProjectName: !Ref ProjectName
        VPCCIDR: !Ref VPCCIDR
        Subnet1CidrBlock: !Ref Subnet1CidrBlock
        Subnet2CidrBlock: !Ref Subnet2CidrBlock
  EFSStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Join 
        - ''
        - - 'https://s3.amazonaws.com/'
          - !Ref SourceBucket
          - /EFSStack.json
      TimeoutInMinutes: '15'
      Parameters:
        ProjectName: !Ref ProjectName
        SecurityGroup1Id: !GetAtt 
          - VPCStack
          - Outputs.SecurityGroup1Id
        SecurityGroup2Id: !GetAtt 
          - VPCStack
          - Outputs.SecurityGroup2Id
        Subnet1Id: !GetAtt 
          - VPCStack
          - Outputs.Subnet1Id
  VPCEndPointsStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Join 
        - ''
        - - 'https://s3.amazonaws.com/'
          - !Ref SourceBucket
          - /VPCEndpointsStack.json
      TimeoutInMinutes: '15'
      Parameters:
        ProjectName: !Ref ProjectName
        VPCId: !GetAtt 
          - VPCStack
          - Outputs.VPCId
        Subnet2Id: !GetAtt 
          - VPCStack
          - Outputs.Subnet2Id
        RouteTableId: !GetAtt 
          - VPCStack
          - Outputs.RouteTableId
        SecurityGroup1Id: !GetAtt 
          - VPCStack
          - Outputs.SecurityGroup1Id
        SecurityGroup2Id: !GetAtt 
          - VPCStack
          - Outputs.SecurityGroup2Id
  ECRStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Join 
        - ''
        - - 'https://s3.amazonaws.com/'
          - !Ref SourceBucket
          - /ECRStack.json
      TimeoutInMinutes: '15'
      Parameters:
        ProjectName: !Ref ProjectName
        ECRRepositoryName: !Ref ECRRepositoryName
        ECREndpoint: !GetAtt 
          - VPCEndPointsStack
          - Outputs.ECREndpoint
  LifecycleConfigStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Join 
        - ''
        - - 'https://s3.amazonaws.com/'
          - !Ref SourceBucket
          - /SageMakerLaunchConfigStack.json
      TimeoutInMinutes: '15'
      Parameters:
        ProjectName: !Ref ProjectName
        EFSMountIpAddr: !GetAtt 
          - EFSStack
          - Outputs.EFSMountIpAddr
  LambdaFunctionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonSageMakerFullAccess'
      Path: /
      RoleName: SagemakerBuildRoles
      Policies:
        - PolicyName: SagemakerBuildPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: SagemakerBuildAction
                Effect: Allow
                Action:
                  - 'iam:*'
                  - 'kms:CreateGrant'
                Resource: '*'
              - Sid: LammbdaBasicExecution
                Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource:
                  - !Join 
                    - ''
                    - - 'arn:aws:logs:'
                      - !Ref 'AWS::Region'
                      - ':'
                      - !Ref 'AWS::AccountId'
                      - ':log-group:/aws/lambda/*'
  PythonLayer:
    Type: 'AWS::Lambda::LayerVersion'
    Properties:
      CompatibleRuntimes:
        - python3.6
        - python2.7
      Content:
        S3Bucket: !Ref SourceBucket
        S3Key: PythonModule.zip
      Description: Python layer
      LayerName: !Ref LayerName
  SageMakerFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        S3Bucket: !Ref SourceBucket
        S3Key: SageMaker_Build.zip
      Description: Sage Maker lambda function
      FunctionName: SageMaker_Build
      Handler: lambda_function.lambda_handler
      Layers:
        - !Ref PythonLayer
      MemorySize: 128
      Role: !GetAtt 
        - LambdaFunctionRole
        - Arn
      Runtime: python3.6
      Tags:
        - Key: ProjectName
          Value: !Ref ProjectName
      Timeout: 840
  SageMakerPortfolio:
    Type: 'AWS::ServiceCatalog::Portfolio'
    Properties:
      AcceptLanguage: en
      Description: Sagemaker Portfolio with all Guardrails
      DisplayName: !Ref PortfolioName
      ProviderName: Brillio
      Tags:
        - Key: Name
          Value: !Ref PortfolioName
  SageMakerProduct:
    Type: 'AWS::ServiceCatalog::CloudFormationProduct'
    Properties:
      AcceptLanguage: en
      Description: This product creates SageMaker Product with provided parameter values.
      Distributor: Amazon
      Name: !Ref ProductName
      Owner: Brillio
      ProvisioningArtifactParameters:
        - Description: >-
            This product creates SageMaker Product with provided parameter
            values.
          Info:
            LoadTemplateFromURL: !Join 
              - ''
              - - 'https://s3.amazonaws.com/'
                - !Ref SourceBucket
                - /SagemakerProduct.json
          Name: Version 1
      SupportDescription: Brillio DI Team
      SupportEmail: aws-brillio@brillio.com
      SupportUrl: >-
        https://www.brillio.com/what-we-do/digital-infrastructure/cloud-infrastructure/
      Tags:
        - Key: Name
          Value: !Ref ProductName
  SageMakerProductAssociation:
    Type: 'AWS::ServiceCatalog::PortfolioProductAssociation'
    Properties:
      PortfolioId: !Ref SageMakerPortfolio
      ProductId: !Ref SageMakerProduct
  PortfolioAdminAssociation:
    Type: 'AWS::ServiceCatalog::PortfolioPrincipalAssociation'
    Properties:
      PortfolioId: !Ref SageMakerPortfolio
      PrincipalARN: !Join 
        - ''
        - - 'arn:aws:iam::'
          - !Ref 'AWS::AccountId'
          - ':group/'
          - !Ref AdminGroupName
      PrincipalType: IAM
  PortfolioGroupAssociation:
    Type: 'AWS::ServiceCatalog::PortfolioPrincipalAssociation'
    Properties:
      PortfolioId: !Ref SageMakerPortfolio
      PrincipalARN: !Join 
        - ''
        - - 'arn:aws:iam::'
          - !Ref 'AWS::AccountId'
          - ':group/'
          - !Ref UserGroupName
      PrincipalType: IAM
Outputs:
  VPCStackOutPut:
    Value: !Ref VPCStack
  EFSStackOutPut:
    Value: !Ref EFSStack
  VPCEndPointsStackOutput:
    Value: !Ref VPCEndPointsStack
  ECRStackOutput:
    Value: !Ref ECRStack
  NbInstanceLifecycleConfigStackOutput:
    Value: !Ref LifecycleConfigStack
  PythonLayer:
    Value: !Ref PythonLayer
    Description: Lambda layer ARN
  LambdaFunction:
    Value: !GetAtt 
      - SageMakerFunction
      - Arn
    Description: Lambda function ARN
