// Add steps as necessary for accessing the software, post-configuration, and testing. Don’t include full usage instructions for your software, but add links to your product documentation for that information.
//Should any sections not be applicable, remove them

==== Optionally deploy {partner-product-name} as a Service Catalog product
After the base infrastructure is configured by the CloudFormation template, data scientists and other users can assume the IAM role (SCEndUserrole) or group that was provided in the CloudFormation output when launching the Service Catalog and then launch SageMaker.

NOTE: Be sure to specify the same environment name that is provided in the CloudFormation template.

=== Test the deployment
To test your deployment, see https://docs.aws.amazon.com/sagemaker/latest/dg/gs-console.html[Get Started- with Amazon SageMaker Notebook Instances and SDKs]. 
//Provide any other information of interest to users, especially focusing on areas where AWS or cloud usage differs from on-premises usage.

//Add any other details that will help the customer use the software on AWS.
