AWSTemplateFormatVersion: 2010-09-09
Description: SageMaker Lambda Function Setup (qs-1qojf6qdk)
Metadata:
  "AWS::CloudFormation::Interface":
    ParameterGroups:
      - Label:
          default: Environment Details
        Parameters:
          - ENVName
      - Label:
          default: AWS Quick Start Configuration
        Parameters:
          - QSS3BucketName
          - QSS3KeyPrefix
    ParameterLabels:
      ENVName:
        default: Environment Name
      QSS3BucketName:
        default: Quick Start S3 Bucket Name
      QSS3KeyPrefix:
        default: Quick Start S3 Key Prefix
Parameters:
  ENVName:
    Description: SageMaker Project name
    Type: String
  RandomStringArn:
    Description: The ARN for the function that will generate the random value to be used in the naming of the S3 Buckets
    Type: String
  QSS3BucketName:
    AllowedPattern: "^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$"
    ConstraintDescription: >-
      Quick Start bucket name can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-).
    Description: S3 bucket name for the Quick Start assets.
    Type: String
    Default: aws-quickstart
  QSS3KeyPrefix:
    AllowedPattern: "^[0-9a-zA-Z-/]*$"
    ConstraintDescription: >-
      Quick Start key prefix can include numbers, lowercase letters, uppercase
      letters, hyphens (-), and forward slash (/).
    Description: "The S3 key prefix for the Quick Start assets. The Quick Start key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slash (/)."
    Type: String
    Default: deployment/
Resources:
  RandomString:
    Type: Custom::RandomString
    Properties:
      ServiceToken: !Ref RandomStringArn
      Number: 8
  LambdaFunctionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      Tags:
        - Key: Environment
          Value: !Join 
            - ''
            - - !Ref ENVName
              - !Sub ${RandomString} 
        - Key: Name
          Value: !Join 
            - ''
            - - !Ref ENVName
              - !Sub ${RandomString}
              - SagemakerBuildRoles
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonSageMakerFullAccess'
      Path: /
      Policies:
        - PolicyName: !Join 
            - ''
            - - !Ref ENVName
              - !Sub ${RandomString}  
              - SagemakerBuildPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: SagemakerBuildAction
                Effect: Allow
                Action:
                  - 'iam:*'
                  - 'kms:CreateGrant'
                Resource: '*'
              - Sid: SagemakerBucketCleanUp
                Effect: Allow
                Action:
                  - 's3:*'
                Resource:
                  - 'arn:aws:s3:::*sagemaker*'
                  - 'arn:aws:s3:::*sagemaker*/*'
              - Sid: LammbdaBasicExecution
                Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource:
                  - !Join 
                    - ''
                    - - 'arn:aws:logs:'
                      - !Ref 'AWS::Region'
                      - ':'
                      - !Ref 'AWS::AccountId'
                      - ':log-group:/aws/lambda/*'
  PythonLayer:
    Type: 'AWS::Lambda::LayerVersion'
    Properties:
      CompatibleRuntimes:
        - python3.6
        - python2.7
      Content:
        S3Bucket: !Ref QSS3BucketName
        S3Key: !Join
          - ''
          - - !Ref QSS3KeyPrefix
            - functions/packages/Boto3/PythonModule.zip
      Description: Python layer
      LayerName: !Join 
        - ''
        - - !Ref ENVName
          - !Sub ${RandomString}  
          - Boto3Layer
  SageMakerFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        S3Bucket: !Ref QSS3BucketName
        S3Key: !Join
          - ''
          - - !Ref QSS3KeyPrefix
            - functions/SageMakerBuild.zip
      Description: Sage Maker lambda function
      FunctionName: !Join 
        - ''
        - - !Ref ENVName
          - !Sub ${RandomString} 
          - '-SageMakerBuild'
      Handler: lambda_function.lambda_handler
      Layers:
        - !Ref PythonLayer
      MemorySize: 128
      Role: !GetAtt 
        - LambdaFunctionRole
        - Arn
      Runtime: python3.6
      Tags:
        - Key: ENVName
          Value: !Join 
            - ''
            - - !Ref ENVName
              - !Sub ${RandomString}
      Timeout: 840
Outputs:
  PythonLayer:
    Value: !Ref PythonLayer
    Description: Lambda layer ARN
  LambdaFunction:
    Value: !GetAtt 
      - SageMakerFunction
      - Arn
    Export:
      Name: !Join [ '', [ SageMakerFunctionArnSM, - !Sub ${RandomString} ] ]
    Description: Lambda function ARN
  LambdaFunctionRole:
    Value: !Ref LambdaFunctionRole
    Description: Lambda function Role
