AWSTemplateFormatVersion: 2010-09-09
Description: NotebookInstance LifecycleConfig (qs-1qojf6qdr)
Metadata:
  "AWS::CloudFormation::Interface":
    ParameterGroups:
      - Label:
          default: Environment Details
        Parameters:
          - ENVName
      - Label:
          default: Launch Configuration Details
        Parameters:
          - EFSMountIpAddr
    ParameterLabels:
      ENVName:
        default: Environment Name
      EFSMountIpAddr:
        default: EFS mount target Ip address
Parameters:
  ENVName:
    Description: SageMaker Project name
    Type: String
  EFSMountIpAddr:
    Description: EFS mount target Ip address
    Type: String
Resources:
  EFSLifecycleConfig:
    Type: 'AWS::SageMaker::NotebookInstanceLifecycleConfig'
    Properties:
      NotebookInstanceLifecycleConfigName: !Join 
        - ''
        - - !Ref ENVName
          - '-EFS-LC'
      OnCreate:
        - Content: !Base64 
            'Fn::Join':
              - ''
              - - |
                  #!/bin/bash 
                - |
                  sudo -u ec2-user -i 
                - |
                  # Creating the directory for EFS 
                - |
                  sudo mkdir /home/ec2-user/SageMaker/efs 
                - |
                  #Mount The EFS to that directory
                - !Sub >
                  sudo mount -t nfs -o
                  nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2
                  ${EFSMountIpAddr}:/ /home/ec2-user/SageMaker/efs 
                - |
                  # Permission chnage 
                - >-
                  sudo chown ec2-user:ec2-user /home/ec2-user/SageMaker/efs
                  --recursive
Outputs:
  NbInstanceLifecycleConfigId:
    Value: !Ref EFSLifecycleConfig
