AWSTemplateFormatVersion: 2010-09-09
Description: SageMaker Service Catalog Setup (qs-1qojf6qen)
Metadata:
  "AWS::CloudFormation::Interface":
    ParameterGroups:
      - Label:
          default: Environment Details
        Parameters:
          - ENVName
      - Label:
          default: AWS Quick Start Configuration
        Parameters:
          - QSS3BucketName
          - QSS3KeyPrefix
      - Label:
          default: Access to Service Catalog
        Parameters:
          - RoleName
          - IAMGroupName
    ParameterLabels:
      RoleName:
        default: Role Name
      IAMGroupName:
        default: IAM Group Name
      ENVName:
        default: Environment Name
      QSS3BucketName:
        default: Quick Start S3 Bucket Name
      QSS3KeyPrefix:
        default: Quick Start S3 Key Prefix
Parameters:
  ENVName:
    Description: SageMaker Project name
    Type: String
  QSS3BucketName:
    AllowedPattern: "^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$"
    ConstraintDescription: >-
      Quick Start bucket name can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-).
    Description: S3 bucket name for the Quick Start assets.
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: "^[0-9a-zA-Z-/]*$"
    ConstraintDescription: >-
      Quick Start key prefix can include numbers, lowercase letters, uppercase
      letters, hyphens (-), and forward slash (/).
    Description: "The S3 key prefix for the Quick Start assets. The Quick Start key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slash (/)."
    Type: String
  RoleName:
    Description: Admin group Name.
    Type: String
  IAMGroupName:
    Description: User group name who will access Service Catalog
    Type: String
    Default: ""
Conditions:
  IAMGroupCondition: !Not 
    - !Equals 
      - ""
      - !Ref IAMGroupName
Resources:
  SCEndUserRole:
    Type: 'AWS::IAM::Role'
    Properties:
      Description: Provides full access to service catalog enduser capabilities
      RoleName: !Join 
        - '-'
        - - !Ref ENVName
          - SC
          - !Ref RoleName
      Tags:
        - Key: Environment
          Value: !Ref ENVName
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - sagemaker.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AWSServiceCatalogEndUserFullAccess'
  SCLaunchRole:
    Type: 'AWS::IAM::Role'
    Properties:
      Description: Provides full access to service catalog to launch product
      RoleName: !Join 
        - '-'
        - - !Ref ENVName
          - SCLaunch
          - !Ref RoleName
      Tags:
        - Key: Environment
          Value: !Ref ENVName
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - servicecatalog.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: !Join 
            - '-'
            - - !Ref ENVName
              - SCLaunchPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: LambdaInvokePermission
                Effect: Allow
                Action:
                  - 'lambda:InvokeFunction'
                Resource: '*'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/IAMFullAccess'
        - 'arn:aws:iam::aws:policy/AmazonS3FullAccess'
        - 'arn:aws:iam::aws:policy/AWSCloudFormationFullAccess'
  SCUserGroup:
    Type: 'AWS::IAM::Group'
    Condition: IAMGroupCondition
    Properties:
      GroupName: !Join 
        - '-'
        - - !Ref ENVName
          - SC
          - !Ref IAMGroupName
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AWSServiceCatalogEndUserFullAccess'
  SageMakerPortfolio:
    Type: 'AWS::ServiceCatalog::Portfolio'
    Properties:
      AcceptLanguage: en
      Description: Sagemaker Portfolio with all Guardrails
      DisplayName: !Join 
        - ''
        - - !Ref ENVName
          - _SageMakerPortfolio
      ProviderName: Brillio
      Tags:
        - Key: Name
          Value: !Join 
            - ''
            - - !Ref ENVName
              - _SageMakerPortfolio
        - Key: ENVName
          Value: !Ref ENVName
  SageMakerProduct:
    Type: 'AWS::ServiceCatalog::CloudFormationProduct'
    Properties:
      AcceptLanguage: en
      Description: This product creates SageMaker Product with provided parameter values.
      Distributor: Amazon
      Name: !Join 
        - ''
        - - !Ref ENVName
          - _SageMakerProduct
      Owner: Brillio
      ProvisioningArtifactParameters:
        - Description: >-
            This product creates SageMaker Product with provided parameter
            values.
          Info:
            LoadTemplateFromURL: !Sub >-
              https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}templates/SagemakerProduct.yaml
          Name: Version 1
      SupportDescription: Brillio DI Team
      SupportEmail: aws-brillio@brillio.com
      SupportUrl: >-
        https://www.brillio.com/what-we-do/digital-infrastructure/cloud-infrastructure/
      Tags:
        - Key: Name
          Value: !Join 
            - ''
            - - !Ref ENVName
              - _SageMakerProduct
        - Key: ENVName
          Value: !Ref ENVName
  SageMakerProductAssociation:
    Type: 'AWS::ServiceCatalog::PortfolioProductAssociation'
    Properties:
      PortfolioId: !Ref SageMakerPortfolio
      ProductId: !Ref SageMakerProduct
  PortfolioRoleAssociation:
    Type: 'AWS::ServiceCatalog::PortfolioPrincipalAssociation'
    Properties:
      PortfolioId: !Ref SageMakerPortfolio
      PrincipalARN: !GetAtt 
        - SCEndUserRole
        - Arn
      PrincipalType: IAM
  PortfolioGroupAssociation:
    Type: 'AWS::ServiceCatalog::PortfolioPrincipalAssociation'
    Condition: IAMGroupCondition
    Properties:
      PortfolioId: !Ref SageMakerPortfolio
      PrincipalARN: !GetAtt 
        - SCUserGroup
        - Arn
      PrincipalType: IAM
  SCLaunchRoleConstraint:
    Type: AWS::ServiceCatalog::LaunchRoleConstraint
    Properties: 
      AcceptLanguage: en
      Description: Role to create SageMaker product
      PortfolioId: !Ref SageMakerPortfolio
      ProductId: !Ref SageMakerProduct
      RoleArn: !GetAtt 
        - SCLaunchRole
        - Arn
Outputs:
  SageMakerPortfolio:
    Value: !Ref SageMakerPortfolio
    Description: SageMaker Portfolio
  SageMakerProduct:
    Value: !Ref SageMakerProduct
    Description: SageMaker Product
  SCEndUserRole:
    Value: !Ref SCEndUserRole
    Description: Provides access to enduser for launching the SageMaker product
  
